### PR TITLE
v18.12.1 qode

### PR DESCRIPTION
**Pull request by sedwards2009**
Qode for nodejs v18.12.1. The changes from the 16.x qode branch have been applied, fixed a little, and squashed down.

The result seems to run ok, but needs more testing first.

### CODE REVIEW

**Comment by sedwards2009** [comment]
This was able to run the small demo NodeGui app.

**Comment by sedwards2009** [comment]
I'm not convinced the GH Actions are running on this PR.

**Comment by a7ul** [comment]
Think current source code change only runs them 
when a release is created
```
on:
  release:
    types: [created]
```
We could create a alpha release like v18.12.1-alpha.0, v18.12.1-alpha.1 etc to test and finallydo a full release?

**Comment by sedwards2009** [comment]
So far I've only built it on Linux here. I can try Windows later today. Mac is a different problem because I don't have mac machine here handy.

**Comment by a7ul** [comment]
cool, i can run mac locally (i have a work laptop that i can use) could you try releasing a build by creating a release from this bramch as v1.18.0-alpha.0 ?

**Comment by a7ul** [comment]
@sedwards2009  it compiled on the mac and I could run it 😄

**Comment by sedwards2009** [comment]
I was able to compile it here on Windows and run it and get the REPL. 👍

**Comment by sedwards2009** [comment]
I guess we can merge this, change the default branch, and tag an alpha.

**Comment by sedwards2009** [comment]
@a7ul It's merged but I don't have the rights to change the default branch on this repo. Can you set the default branch plz?

**Comment by a7ul** [comment]
updated and gave you the rights too

**Comment by sedwards2009** [comment]
Thanks. I'll tag it and create a `rc1` release.

**Comment by sedwards2009** [comment]
Having a release out there will make the Qt6 work easier.

**Comment by sedwards2009** [comment]
@a7ul Everything is finally built, do you have to manually publish the package to npmjs?

**Comment by a7ul** [comment]
Ah yes, let me do that

**Comment by a7ul** [comment]
@sedwards2009  can you send your npm username, I can add you to the npm org

**Comment by sedwards2009** [comment]
I'm sedwards2009 on npmjs.

thanks

**Pull request merged**
